### ISSUE TITLE
snip

### ISSUE THREAD

**Issue by okureta** [xrivendell/PCSGOLH#8]
snip

**Comment by ElectfriedTheGod** [comment]
![csgo_KF9J5cb1GQ](https://user-images.githubusercontent.com/37424196/63595625-a5cd0380-c576-11e9-992c-2c825b483db1.png)
![firefox_IIePIrXtRm](https://user-images.githubusercontent.com/37424196/63595636-aa91b780-c576-11e9-8eb2-00d88cda9c74.png)
